# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9f00081d74bfeb387b1ebd182bd7ca859e22e940bf670615c848037f3edad71fc62b62a9e581a6fabbe580e28a9145fad52b826c595a2336e063d0c48aee1a3

test:
  secret_key_base: 04cec258d2a94717013e471ca20a12dc881854f957339f37c9d30d748959aacbcafd4e5614ad37d1b9579666b1ff3be675649a198d42f5cdb27b8edd300b4e35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
